# Generated by Django 3.1.2 on 2020-10-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='data_format',
            field=models.JSONField(null=True),
        ),
    ]
