# Generated by Django 3.1.2 on 2020-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0005_device_thing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='thing_name',
        ),
        migrations.AddField(
            model_name='device',
            name='aws_thing_name',
            field=models.CharField(default='placeholder', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
