# Generated by Django 3.1.2 on 2020-10-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0006_auto_20201013_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='registration_date',
            new_name='registration_datetime',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
