# Generated by Django 3.1.2 on 2020-10-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0007_auto_20201014_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='datetime',
            new_name='receiving_datetime',
        ),
    ]
