# Generated by Django 3.1.2 on 2020-10-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0008_auto_20201014_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='receiving_datetime',
            new_name='reception_datetime',
        ),
    ]
