# Generated by Django 3.1.2 on 2020-10-15 08:17

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0009_auto_20201014_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registration_datetime',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
