# Generated by Django 3.1.2 on 2020-10-20 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0010_auto_20201015_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 12, 49, 31, 532892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='reception_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 12, 49, 31, 533485, tzinfo=utc)),
        ),
    ]
