# Generated by Django 3.1.2 on 2020-11-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_backend', '0012_auto_20201020_1251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together=set(),
        ),
    ]
